version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./.db.env
    networks:
      - bill-sharing-network
networks:
  bill-sharing-network:
    driver: bridge