version: "3"
services:
  nodeapp:
    container_name: bill-sharing
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - bill-sharing-network
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./.db.env
    networks:
      - bill-sharing-network
networks:
  bill-sharing-network:
    driver: bridge